[package]
name = "hive-cli"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "hive"
path = "src/main.rs"

[dependencies]
clap = { version = "4.4", features = ["derive"] }
hive-codegen = { path = "../hive-codegen" }
