[package]
name = "hive-db"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0"
sqlx = { version = "0.8.6", features = ["postgres", "runtime-tokio-native-tls", "macros"] }
urlencoding = "2.1"